/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.codecraftuk.words;

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void topWords() {
        var words = List.of(new Tuple<String, Integer>("mr", 786));
        var app = new App();
        assert(app.topWords()).equals(words);
    }
}
